const Countries = [
    "United States", "Canada", "United Kingdom", "Australia", "Germany",
    "France", "Italy", "Spain", "Japan", "China", "India", "Brazil", "Mexico",
    "South Korea", "Russia", "Argentina", "Turkey", "Saudi Arabia", "South Africa",
    "Nigeria", "Egypt", "Indonesia", "Thailand", "Vietnam", "Malaysia",
    "Philippines", "Sweden", "Norway", "Finland", "Denmark", "Netherlands",
    "Belgium", "Switzerland", "Austria", "Greece", "Poland", "Hungary",
    "Czech Republic", "Portugal", "Israel", "United Arab Emirates", "Qatar",
    "Kuwait", "Oman", "Singapore", "New Zealand", "Chile", "Peru", "Colombia",
    "Venezuela",  "Ukraine", "Belarus", "Kazakhstan", "Uzbekistan", "Tajikistan",
    "Kyrgyzstan", "Turkmenistan", "Azerbaijan", "Georgia", "Armenia", "Moldova",
    "Bulgaria", "Romania", "Croatia", "Serbia", "Bosnia and Herzegovina",
    "Montenegro", "Albania", "Macedonia", "Kosovo", "Slovenia", "Slovakia",
    "Belarus", "Latvia", "Lithuania", "Estonia", "Ireland", "Iceland", "Greenland",
    "Malta", "Cyprus", "Andorra", "Monaco", "San Marino", "Luxembourg",
    "Liechtenstein", "Vatican City", "Yemen", "Syria", "Lebanon", "Jordan",
    "Iraq", "Iran", "Afghanistan", "Pakistan", "Bangladesh", "Nepal", "Sri Lanka",
    "Bhutan", "Maldives",    "Somalia", "Djibouti", "Eritrea", "Sudan", "South Sudan", "Ethiopia",
    "Kenya", "Uganda", "Rwanda", "Burundi", "Tanzania", "Seychelles",
    "Mauritius", "Madagascar", "Comoros", "Mozambique", "Zimbabwe",
    "Zambia", "Malawi", "Botswana", "Namibia", "Angola", "Lesotho", "Swaziland",
    "South Africa", "Morocco", "Algeria", "Tunisia", "Libya", "Egypt",
    "Western Sahara", "Mali", "Niger", "Chad", "Sudan", "Eritrea", "Djibouti",
    "Somalia", "Equatorial Guinea", "Cameroon", "Central African Republic",
    "Democratic Republic of the Congo", "Republic of the Congo", "Gabon",
    "São Tomé and Príncipe", "Equatorial Guinea", "Benin", "Togo", "Nigeria",
    "Ghana", "Côte d'Ivoire", "Liberia", "Sierra Leone", "Guinea-Bissau",
    "Guinea", "Senegal", "The Gambia", "Mauritania", "Western Sahara",
    "Mali", "Burkina Faso", "Niger", "Chad", "Sudan", "Eritrea", "Djibouti",
    "Somalia", "Ethiopia", "South Sudan", "Uganda", "Kenya", "Tanzania",
    "Rwanda", "Burundi", "Seychelles", "Mauritius", "Comoros", "Mozambique",
    "Zimbabwe", "Zambia", "Malawi", "Botswana", "Namibia", "Angola", "Lesotho",
    "Swaziland", "South Africa", "Mauritania", "Mali", "Niger", "Chad",
    "Sudan", "Eritrea", "Djibouti", "Somalia", "Ethiopia", "Kenya", "Uganda",
    "Tanzania", "Rwanda", "Burundi", "Seychelles", "Mauritius", "Madagascar",
    "Comoros", "Mozambique", "Zimbabwe", "Zambia", "Malawi", "Botswana",
    "Namibia", "Angola", "Lesotho", "Swaziland", "South Africa"
  ];
  
